### ISSUE TITLE
online tic tac toe

### ISSUE THREAD

**Issue by JesperKauppinen** [DevJamGroup/Projects-List#8]
## Name
Tic Tac Toe

## Difficulty 
Advanced

## 📝 Project Description
Tic-tac-toe, noughts and crosses, or Xs and Os is a paper-and-pencil game for two players who take turns marking the spaces in a three-by-three grid with X or O. The player who succeeds in placing three of their marks in a horizontal, vertical, or diagonal row is the winner.

## 📑User Stories
- [ ] User sees 3x3 grid
- [ ] User can click on one of the 9 boxes and there will be an X drawn
- [ ] When user clicks again there will be an O drawn
- [ ] User can play online with others (use websockets or real time api or any other implementation you want that allows you to real time send and receive data)
- [ ] When one user has lined three marks (X or O) horizontaly, vertically or diagonally they win and the game starts again

## 🌟 Bonus features (optional)
- [ ] User can choose between singleplayer and multiplayer 
- [ ] User can play against a friend in private session (shared link)
- [ ] User can log in or just type username (your choice)
- [ ] Scoreboard will show who has most wins and games played
- [ ] User can play against bot

## Useful links and resources
- [wikipedia](https://en.wikipedia.org/wiki/Tic-tac-toe)
- [Socket io](https://socket.io/)

## Example projects
- [Google tic tac toe](https://www.google.com/search?client=firefox-b-d&q=tic+tac+toe)
- [Github projects](https://github.com/topics/tic-tac-toe-game)

**Comment by StoneCypher** [comment]
>  User can play online with others (use websockets)

yeah i'm going to push back against this

websockets are basically the worst available communications choice for a game like tic tac toe

this should be a simple api hit (or better yet, you should let people choose how they want to do it)
